name: Build and Run Tests

on:
  push:
    branches:
      - '**'

jobs:
  setup:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12' 

    - name: Install Kerberos tools
      run: |
        sudo apt-get update
        sudo apt-get install -y krb5-user

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Run tests
      run: |
        chmod +x run-tests.sh
        ./run-tests.sh

    - name: Build package to publish
      run: |
        .venv/bin/python setup.py sdist bdist_wheel

    - name: Freeze packages
      run: |
          .venv/bin/pip freeze > requirements.txt

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: dist
          path: dist

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
          name: requirements.txt
          path: requirements.txt
        

          
